name 'hirez-etcd'
version '1.0.0'
source 'https://github.com/hirez/etcd-puppet-module'
author 'hirez'
license 'Apache License, Version 2.0'
summary 'Make etcd calls from puppet.'
description 'Installs and configures etcd'
project_page 'https://github.com/hirez/etcd-puppet-module'
